name: jaydenfu
version: 1

libraries:
- name: "django"
  version: "1.8.3"

handlers:
- url: /static
  static_dir: static

cron:
- description: cron weather
  url: /tools/weather-get-data
  schedule: 0 0-23/3 * * *
  timezone: Beijing
